export const env = {
  SUPABASE_URL: process.env.SUPABASE_URL!,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY!,
  WHATSAPP_TOKEN: process.env.WHATSAPP_TOKEN!,
  STEADFAST_API_KEY: process.env.STEADFAST_API_KEY!,
  STEADFAST_SECRET_KEY: process.env.STEADFAST_SECRET_KEY!,
}
